/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_vamp_plugins_Plugin_InputDomain */

#ifndef _Included_org_vamp_plugins_Plugin_InputDomain
#define _Included_org_vamp_plugins_Plugin_InputDomain
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
