/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_vamp_plugins_PluginLoader */

#ifndef _Included_org_vamp_plugins_PluginLoader
#define _Included_org_vamp_plugins_PluginLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_vamp_plugins_PluginLoader
 * Method:    loadPluginNative
 * Signature: (Ljava/lang/String;F)J
 */
JNIEXPORT jlong JNICALL Java_org_vamp_1plugins_PluginLoader_loadPluginNative
  (JNIEnv *, jobject, jstring, jfloat);

/*
 * Class:     org_vamp_plugins_PluginLoader
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_vamp_1plugins_PluginLoader_initialise
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
