/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_vamp_plugins_PluginLoader_LoadFailedException */

#ifndef _Included_org_vamp_plugins_PluginLoader_LoadFailedException
#define _Included_org_vamp_plugins_PluginLoader_LoadFailedException
#ifdef __cplusplus
extern "C" {
#endif
#undef org_vamp_plugins_PluginLoader_LoadFailedException_serialVersionUID
#define org_vamp_plugins_PluginLoader_LoadFailedException_serialVersionUID -3042686055658047285LL
#undef org_vamp_plugins_PluginLoader_LoadFailedException_serialVersionUID
#define org_vamp_plugins_PluginLoader_LoadFailedException_serialVersionUID -3387516993124229948LL
#ifdef __cplusplus
}
#endif
#endif
