/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_vamp_plugins_PluginLoader */

#ifndef _Included_org_vamp_plugins_PluginLoader
#define _Included_org_vamp_plugins_PluginLoader
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_org_vamp_1plugins_PluginLoader_loadPluginNative
(JNIEnv *, jobject, jstring, jfloat, jint);

JNIEXPORT jobjectArray JNICALL Java_org_vamp_1plugins_PluginLoader_listPlugins
(JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_org_vamp_1plugins_PluginLoader_initialise
(JNIEnv *, jobject);

JNIEXPORT jobjectArray JNICALL Java_org_vamp_1plugins_PluginLoader_getPluginCategory
(JNIEnv *, jobject, jstring);

JNIEXPORT jobjectArray JNICALL Java_org_vamp_1plugins_PluginLoader_getPluginPath
(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
