/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_vamp_plugins_Plugin */

#ifndef _Included_org_vamp_plugins_Plugin
#define _Included_org_vamp_plugins_Plugin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_vamp_plugins_Plugin
 * Method:    getIdentifier
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_vamp_1plugins_Plugin_getIdentifier
  (JNIEnv *, jobject);

/*
 * Class:     org_vamp_plugins_Plugin
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_vamp_1plugins_Plugin_getName
  (JNIEnv *, jobject);

/*
 * Class:     org_vamp_plugins_Plugin
 * Method:    getDescription
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_vamp_1plugins_Plugin_getDescription
  (JNIEnv *, jobject);

/*
 * Class:     org_vamp_plugins_Plugin
 * Method:    getPluginVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_vamp_1plugins_Plugin_getPluginVersion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
